---
kind: Template
apiVersion: v1
metadata:
  name: speed-cases-svc-pipeline
  annotations:
    description:
    tags: speed
    iconClass: icon-nodejs
    template.openshift.io/bindable: 'false'
labels:
  template: speed-cases-svc-pipeline
objects:

- kind: ImageStream
  apiVersion: v1
  metadata:
    name: "${NAME}"
    annotations:
      description: Keeps track of changes in the application image

- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${NAME}
    name: ${NAME}
  spec:
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      type: Git
      git:
        uri: "git@github.com:Steampunk-SPEED/speed-cases.git"
        ref: "develop"
      sourceSecret:
        name: github-key
    strategy:
      dockerStrategy:
        dockerfilePath: Dockerfile
        env:
          - name: "GIT_SSL_NO_VERIFY"
            value: "true"
          - name: SPEED_REPO_URL
            value: ${SPEED_REPO_URL}
          - name: SPEED_REPO_USER
            valueFrom:
              secretKeyRef:
                key: username
                name: speed-repo-credentials
          - name: SPEED_REPO_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: speed-repo-credentials
      type: Docker
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}:latest
    triggers: []


parameters:
- name: SPEED_REPO_URL
  displayName: Nexus Repo URL
  value: 'https://nexus-ci.speedc2c24.steampunkfoundry.net/repository/maven-releases/'
- name: NAME
  displayName: Name
  description: The name assigned to all of the frontend objects defined in this template.
  required: true
  value: speed-cases-svc
- name: CI_NAME
  displayName: CI name
  required: true
  value: speed-cases-svc-ci
- name: FUNCTIONAL_NAME
  displayName: FUNCTIONAL name
  required: true
  value: speed-cases-svc-functional
- name: STAGING_NAME
  displayName: STAGING name
  required: true
  value: speed-cases-svc-staging
- name: NAMESPACE
  displayName: Namespace
  description: The OpenShift Namespace where the ImageStream resides.
  required: true
  value: ci
- name: SSH_KEY_NAME
  displayName: SSH key for git checkout
  required: true
  value: ci-openshiftkey
- name: CONTEXT_DIR
  displayName: Context Directory
  description: Set this to the relative path to your cases if it is not in the root
    of your repository.
- name: SPRING_BOOT_ARTIFACT
  displayName: Spring Boot Artifact filename
  value: 'cases-0.0.1-SNAPSHOT.jar'
