zuul:
  #Service will be mapped under the /api URI
  #prefix: /api/data
  sensitive-headers: Cookie,Set-Cookie

  routes:
    projects:
      path: /service1/**
      url: http://localhost:9016/
    users:
      path: /users/**
      url: http://localhost:9011/
    documents:
      path: /documents/**
      url: http://localhost:9012/
    cis-data:
      path: /cis-data/**
      url: http://localhost:9012/
    analytics:
      path: /analytics/**
      url: https://8demkt6183.execute-api.us-east-2.amazonaws.com/analytics
