service: analytics-serverless

frameworkVersion: ">=2.1.0 <3.0.0"

provider:
  name: aws
  runtime: nodejs12.x

functions:
  fetchToken:
    handler: main.handler
    events:
      - http:
          path: /
          method: get
