FROM public.ecr.aws/lambda/nodejs:12

# Copy function code
COPY src/ /var/task/

RUN npm install

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "main.handler" ]