---
kind: Template
apiVersion: v1
metadata:
  name: speed-forms-svc-integration
  annotations:
    description:
    tags: speed
    template.openshift.io/bindable: 'false'
labels:
  template: speed-forms-svc-integration
objects:

- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: ${DB_NAME}
    name: ${DB_NAME}
  spec:
    ports:
      - name: client
        port: ${{MONGO_PORT}}
        protocol: TCP
        targetPort: ${{MONGO_PORT}}
    selector:
      app: ${DB_NAME}
    sessionAffinity: None
    type: ClusterIP

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    name: ${DB_NAME}
    labels:
      app: ${DB_NAME}
  spec:
    replicas: 1
    selector:
      app: ${DB_NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: ${DB_NAME}
      spec:
        containers:
        - image: " "
          name: mongo
          imagePullPolicy: Always
          ports:
            - containerPort: 27017
              protocol: TCP
          resources:
            limits:
              memory: ${MEMORY_LIMIT}
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
    triggers:
    - imageChangeParams:
        automatic: false
        containerNames:
        - mongo
        from:
          kind: ImageStreamTag
          name: "mongo:latest"
          namespace: "ci"
      type: ImageChange
    - type: ConfigChange

parameters:
- name: SVC_IMAGE_NAME
  displayName: Image name
  description: Name of docker image to deploy
  required: true
  value: ''
- name: SVC_NAME
  displayName: Microservice name
  description: The name assigned to all of the frontend objects defined in this template.
  required: true
  value: ''
- name: SVC_IMAGE_TAG
  displayName: Service Docker Image Tag
  description: Tag corresponding to environment
  required: true
  value: ''
- name: NAMESPACE
  displayName: Namespace
  description: The OpenShift Namespace where the ImageStream resides.
  required: true
  value: ''
- name: MEMORY_LIMIT
  displayName: Memory Limit
  description: Maximum amount of memory the Node.js container can use.
  required: true
  value: 1Gi
- description: Mongo service name
  displayName: Mongo service name
  name: DB_NAME
  required: true
  value: ''
- description: Mongo endpoint
  displayName: Mongo endpoint
  name: MONGO_HOST
  required: true
  value: ""
- description: Mongo port
  displayName: Mongo port
  name: MONGO_PORT
  required: true
  value: "27017"
