#!/bin/bash

# Create forms service user
mongo $MONGO_INITDB_DATABASE --host localhost <<EOF
  db.createUser({
    user: "$MONGO_INITDB_ROOT_USERNAME",
    pwd: "$MONGO_INITDB_ROOT_PASSWORD",
    roles: [
      {
        role: 'readWrite',
        db: "$MONGO_INITDB_DATABASE"
      }, {
        role: '__system',
        db: "admin"
      }
    ]
  }),
    db.form.insertMany([
 {
   "anumber": "A000000001",
   "applicantId":"470b6681-2d1e-49c4-94b9-9c3647200c55",
   "submissionStatus": "SUBMITTED",
   "submissionDate":"03/28/2021",
   "formNumber":"2021_I131_X1",
   "fieldControlOffice": "BCA",
   "dateFileOpen": "02/28/2021",
   "lastName": "Traveler",
   "firstName": "Tomas",
   "middleName": "Taylor",
   "mother": "Lucille",
   "father": "Desi",
   "akaLastName": null,
   "akaFirstName": null,
   "inCareOf": null,
   "address": "1005 Ferry Street",
   "address2": "Apt. 16",
   "city": "Dayton",
   "state": "OR",
   "zipCode": "97114",
   "postalCode": null,
   "province": null,
   "country": "USA",
   "countryOfBirth": "Argentina",
   "countryOfCitizenship": "Argentina",
   "visaClass": "B2 - NONIMMIGRANT (VISTOR VISA)",
   "portofEntry": "PDX",
   "dateofEntry": "06/12/2018",
   "dateOfBirth": "01/01/1989",
   "gender": "MALE",
   "ssn": null,
   "i94AdministeredNumbered": 123456789101,
   "passportNumber": "A6J0KRV22ZVP9Y32ADC5",
   "fbiNumber": "121347000000",
   "driversLicenseNumber": "QGR06HZWXT107UCJS89B",
   "fingerPrintCode": null,
   "identificationFin": 9631,
   "applicationType": "ONE_D",
   "numberOfTrips": "One Trip",
   "explanationOfEligibility": "I have married a US Citizen recently and submitted my Green Card packet to include Forms I-485, I-130, I-1765 and this I-131 together. I am waiting on my Green Card now.",
   "signature": null,
   "signatureDate": "03/24/2021",
   "phoneNumber": "555-555-5555",
   "purposeOfTrip": "My father has major health complications that are progressively worsening. Plan to visit my parents.",
   "countriesVisiting": "Argentina",
   "dateOfDeparture": "09/15/2021",
   "lengthOfTrip": 15,
   "inProceedings": "false",
   "previouslyIssued": "false",
   "deliveryAddress": "1005 Ferry Street",
   "deliveryAddress2": "Apt 16",
   "deliveryCity": "Dayton",
   "deliveryState": "Oregon",
   "deliveryZipCode": "97114",
   "deliveryPostalCode": null,
   "deliveryProvince": null,
   "deliveryCountry": "USA",
   "supportDocument": [{
        "id": "VTIMVESFIPUSARNEFENF",
        "formType": "I-131",
        "name": "Travel Document",
        "dateSubmitted": "03/24/2021",
        "status": "Accepted",
        "url": "ABC_DEFG"
        }
    ]
 },
 {
   "anumber": "A000000003",
   "applicantId":"44839225-53c1-4fb3-998d-189b48c64951",
   "submissionStatus": "SUBMITTED",
   "submissionDate":"03/19/2021",
   "formNumber":"2021_I131_X8",
   "fieldControlOffice": "BCA",
   "dateFileOpen": "02/28/2021",
   "lastName": "Entry",
   "firstName": "Data",
   "middleName": "Taylor",
   "mother": "Lucille",
   "father": "Desi",
   "akaLastName": null,
   "akaFirstName": null,
   "inCareOf": null,
   "address": "1005 Ferry Street",
   "address2": "Apt. 16",
   "city": "Dayton",
   "state": "OR",
   "zipCode": "97114",
   "postalCode": null,
   "province": null,
   "country": "USA",
   "countryOfBirth": "Argentina",
   "countryOfCitizenship": "Argentina",
   "visaClass": "B2 - NONIMMIGRANT (VISTOR VISA)",
   "portofEntry": "PDX",
   "dateofEntry": "06/12/2018",
   "dateOfBirth": "01/01/1989",
   "gender": "MALE",
   "ssn": null,
   "i94AdministeredNumbered": 123456789101,
   "passportNumber": "A6J0KRV22ZVP9Y32ADC5",
   "fbiNumber": "121347000000",
   "driversLicenseNumber": "QGR06HZWXT107UCJS89B",
   "fingerPrintCode": null,
   "identificationFin": 9631,
   "applicationType": "ONE_D",
   "numberOfTrips": "One Trip",
   "explanationOfEligibility": "I have married a US Citizen recently and submitted my Green Card packet to include Forms I-485, I-130, I-1765 and this I-131 together. I am waiting on my Green Card now.",
   "signature": null,
   "signatureDate": "03/24/2021",
   "phoneNumber": "555-555-5555",
   "purposeOfTrip": "My father has major health complications that are progressively worsening. Plan to visit my parents.",
   "countriesVisiting": "Argentina",
   "dateOfDeparture": "09/15/2021",
   "lengthOfTrip": 15,
   "inProceedings": "false",
   "previouslyIssued": "false",
   "deliveryAddress": "1005 Ferry Street",
   "deliveryAddress2": "Apt 16",
   "deliveryCity": "Dayton",
   "deliveryState": "Oregon",
   "deliveryZipCode": "97114",
   "deliveryPostalCode": null,
   "deliveryProvince": null,
   "deliveryCountry": "USA",
   "supportDocument": [{
        "id": "VTIMVESFIPUSARNEFENF",
        "formType": "I-131",
        "name": "Travel Document",
        "dateSubmitted": "03/24/2021",
        "status": "Accepted",
        "url": "ABC_DEFG"
        }
    ]
 },
 {
   "anumber": "A918073645",
   "applicantId":"8f8ceb3a-bcfe-4dab-9e6e-0a9d6e17497a",
   "submissionStatus": "IN_PROGRESS",
   "submissionDate":null,
   "formNumber":"2021_I131_X2",
   "fieldControlOffice": "OGD",
   "dateFileOpen": "06/06/2019",
   "lastName": "Stovell",
   "firstName": "Zola",
   "middleName": null,
   "mother": "Arlee",
   "father": "Piotr",
   "akaLastName": null,
   "akaFirstName": null,
   "inCareOf": null,
   "address": "2287 Cocquina Drive",
   "address2": null,
   "city": "Reston",
   "state": "VA",
   "zipCode": "20191",
   "postalCode": null,
   "province": null,
   "country": "USA",
   "countryOfBirth": "PGASU",
   "countryOfCitizenship": "UPGSU",
   "visaClass": "DE - PAROLEE (DEFERRED INSPECTION)",
   "portofEntry": "JAI",
   "dateofEntry": "12/21/2017",
   "dateOfBirth": "05/25/1964",
   "gender": "FEMALE",
   "ssn": null,
   "i94AdministeredNumbered": 101987654321,
   "passportNumber": "VTC0LQ1VE56D1P8CL654",
   "fbiNumber": "366852000000",
   "driversLicenseNumber": "LEN8492TM902NN17B8M0",
   "fingerPrintCode": "ENFAQSAPETRTTEASCMTS",
   "identificationFin": 9173,
   "applicationType": "ONE_D",
   "numberOfTrips": "More than one trip",
   "explanationOfEligibility": "My parole is expiring and I am filing for a new one.",
   "signature": null,
   "signatureDate": "02/26/2020",
   "phoneNumber": "571-123-5555",
   "purposeOfTrip": "I would like to attend my sister's wedding and visit additional family members.",
   "countriesVisiting": "Iceland",
   "dateOfDeparture": "05/15/2021",
   "lengthOfTrip": 34,
   "inProceedings": "false",
   "previouslyIssued": "false",
   "deliveryAddress": "1643 Parkcrest Circle",
   "deliveryAddress2": "STE 100",
   "deliveryCity": "Reston",
   "deliveryState": "VA",
   "deliveryZipCode": "20191",
   "deliveryPostalCode": null,
   "deliveryProvince": null,
   "deliveryCountry": "USA",
   "supportDocument": [{
        "id": "SSNSEUESTNRTTSMTSTCS",
        "formType": "I-131",
        "name": "Copy of Driver's License",
        "dateSubmitted": "02/26/2020",
        "status": "Rejected",
        "url": "ACD_BEFG"
        }
    ]
 },
 {
   "anumber": "A827972940",
   "applicantId":"0f5158db-6632-41ba-a4ce-c93c88b0ba9b",
   "submissionStatus": "IN_PROGRESS",
   "submissionDate":null,
   "formNumber":"2021_I131_X3",
   "fieldControlOffice": "VUO",
   "dateFileOpen": "11/02/2018",
   "lastName": "Legros",
   "firstName": "Rudolph",
   "middleName": null,
   "mother": "Elizabet",
   "father": null,
   "akaLastName": "Bins",
   "akaFirstName": null,
   "inCareOf": null,
   "address": "600 W Schuylkill Road",
   "address2": null,
   "city": "Pottstown",
   "state": "PA",
   "zipCode": "19465",
   "postalCode": null,
   "province": null,
   "country": "USA",
   "countryOfBirth": "RECUX",
   "countryOfCitizenship": "PZNBT",
   "visaClass": "DA - ADVANCE PAROLE (DISTRICT AUTH)",
   "portofEntry": "FJQ",
   "dateofEntry": "04/18/2012",
   "dateOfBirth": "10/01/1934",
   "gender": "FEMALE",
   "ssn": "765-140-197",
   "i94AdministeredNumbered": 83266600030,
   "passportNumber": "BE74QF70N805ZT3FIHYY",
   "fbiNumber": "Y23P8JI7ZC1I",
   "driversLicenseNumber": "BABYVAT04OT668D9TNP3",
   "fingerPrintCode": "MPLLLHRYXLDFVPCWDGOR",
   "identificationFin": 5303603504,
   "applicationType": "ONE_D",
   "numberOfTrips": "More than one trip",
   "explanationOfEligibility": "I am on an H-1 temporary work visa.",
   "signature": null,
   "signatureDate": "11/19/2020",
   "phoneNumber": "267-123-5555",
   "purposeOfTrip": "I would like to visit my wife for her birthday.",
   "countriesVisiting": "Bolivia",
   "dateOfDeparture": "07/13/2021",
   "lengthOfTrip": 20,
   "inProceedings": "false",
   "previouslyIssued": "false",
   "deliveryAddress": "600 W Schuylkill Road",
   "deliveryAddress2": null,
   "deliveryCity": "Pottstown",
   "deliveryState": "PA",
   "deliveryZipCode": "19465",
   "deliveryPostalCode": null,
   "deliveryProvince": null,
   "deliveryCountry": "USA",
   "supportDocument": [{
        "id": "HOYDFHXDFZPCUSBRFMPT",
        "formType": "I-131",
        "name": "H1 Visa",
        "dateSubmitted": "11/20/2020",
        "status": "Accepted",
        "url": "GEG_EADH"
        }
    ]
 },
 {
   "anumber": "A232233773",
   "applicantId":"6cef8979-e823-4eae-b85e-7ff9cdd94139",
   "submissionStatus": "IN_PROGRESS",
   "submissionDate":null,
   "formNumber":"2021_I131_X4",
   "fieldControlOffice": "SFC",
   "dateFileOpen": "01/14/2016",
   "lastName": "Lesch",
   "firstName": "Clayton",
   "middleName": "Torphy",
   "mother": "Luetta",
   "father": null,
   "akaLastName": null,
   "akaFirstName": null,
   "inCareOf": null,
   "address": "1625 Roswell Road",
   "address2": null,
   "city": "Marietta",
   "state": "GA",
   "zipCode": "30062",
   "postalCode": null,
   "province": null,
   "country": "USA",
   "countryOfBirth": "ZAJJI",
   "countryOfCitizenship": "JOTVV",
   "visaClass": "DA - ADVANCE PAROLE (DISTRICT AUTH)",
   "portofEntry": "OID",
   "dateofEntry": "02/28/2015",
   "dateOfBirth": "10/14/1950",
   "gender": "MALE",
   "ssn": "531-869-207",
   "i94AdministeredNumbered": 39706416611,
   "passportNumber": "1GI3V3B0UHS4OSPH6LU0",
   "fbiNumber": "O0BQ0R67YWI7",
   "driversLicenseNumber": "LNO0W5TTCSCBFB97N6HY",
   "fingerPrintCode": "IHQEMJPOJHZDNLJJIWNA",
   "identificationFin": 7502904,
   "applicationType": "ONE_D",
   "numberOfTrips": "More than one trip",
   "explanationOfEligibility": "I have a V1 visa and am a spouse of lawful permanent resident.",
   "signature": null,
   "signatureDate": "01/25/2021",
   "phoneNumber": "770-123-5555",
   "purposeOfTrip": "My mother is turning 90 and I would like to attend her birthday to celebrate.",
   "countriesVisiting": "Sweden",
   "dateOfDeparture": "09/19/2021",
   "lengthOfTrip": 20,
   "inProceedings": "false",
   "previouslyIssued": "false",
   "deliveryAddress": "5599 Boggs Drive",
   "deliveryAddress2": null,
   "deliveryCity": "Stone Mountain",
   "deliveryState": "GA",
   "deliveryZipCode": "30087",
   "deliveryPostalCode": null,
   "deliveryProvince": null,
   "deliveryCountry": "USA",
   "supportDocument": [{
        "id": "RMUUFINOYMEBAZKPJZPV",
        "formType": "I-131",
        "name": "V1 Visa",
        "dateSubmitted": "01/25/2021",
        "status": "Accepted",
        "url": "DGO_ESTB"
    }
]
},
{
   "anumber": "A123456789",
   "applicantId":"b8ba171a-3094-4fee-99f1-1984c4d41ff8",
   "submissionStatus": "SUBMITTED",
   "submissionDate":"03/28/2021",
   "formNumber":"1",
   "fieldControlOffice": "BCA",
   "dateFileOpen": "02/28/2021",
   "lastName": "Applicant",
   "firstName": "Test",
   "middleName": "I",
   "mother": "Lucille",
   "father": "Desi",
   "akaLastName": null,
   "akaFirstName": null,
   "inCareOf": null,
   "address": "1005 Ferry Street",
   "address2": "Apt. 16",
   "city": "Dayton",
   "state": "OR",
   "zipCode": "97114",
   "postalCode": null,
   "province": null,
   "country": "USA",
   "countryOfBirth": "Argentina",
   "countryOfCitizenship": "Argentina",
   "visaClass": "B2 - NONIMMIGRANT (VISITOR VISA)",
   "portofEntry": "PDX",
   "dateofEntry": "06/12/2018",
   "dateOfBirth": "01/01/1989",
   "gender": "MALE",
   "ssn": null,
   "i94AdministeredNumbered": 123456789101,
   "passportNumber": "A6J0KRV22ZVP9Y32ADC5",
   "fbiNumber": "121347000000",
   "driversLicenseNumber": "QGR06HZWXT107UCJS89B",
   "fingerPrintCode": null,
   "identificationFin": 9631,
   "applicationType": "ONE_C",
   "numberOfTrips": "One Trip",
   "explanationOfEligibility": "I have married a US Citizen recently and submitted my Green Card packet to include Forms I-485, I-130, I-1765 and this I-131 together. I am waiting on my Green Card now.",
   "signature": null,
   "signatureDate": "03/24/2021",
   "phoneNumber": "555-555-5555",
   "purposeOfTrip": "My father has major health complications that are progressively worsening. Plan to visit my parents.",
   "countriesVisiting": "Argentina",
   "dateOfDeparture": "09/15/2021",
   "lengthOfTrip": 15,
   "inProceedings": "false",
   "previouslyIssued": "false",
   "deliveryAddress": "1005 Ferry Street",
   "deliveryAddress2": "Apt 16",
   "deliveryCity": "Dayton",
   "deliveryState": "Oregon",
   "deliveryZipCode": "97114",
   "deliveryPostalCode": null,
   "deliveryProvince": null,
   "deliveryCountry": "USA",
   "supportDocument": [{
        "id": "VTIMVESFIPUSARNEFENF",
        "formType": "I-131",
        "name": "Travel Document",
        "dateSubmitted": "03/24/2021",
        "status": "Accepted",
        "url": "ABC_DEFG"
        }
    ]
 },
 {
   "anumber": "A918073655",
   "applicantId":"4ba3cf55-05f8-4220-b5f7-0740ba74fc16",
   "submissionStatus": "SUBMITTED",
   "submissionDate":"06/06/2020",
   "formNumber":"2021_I131_X9",
   "fieldControlOffice": "OGD",
   "dateFileOpen": "06/06/2019",
   "lastName": "Rajma",
   "firstName": "Ritu",
   "middleName": null,
   "mother": "Arlee",
   "father": "Piotr",
   "akaLastName": null,
   "akaFirstName": null,
   "inCareOf": null,
   "address": "2287 Cocquina Drive",
   "address2": null,
   "city": "Reston",
   "state": "VA",
   "zipCode": "20191",
   "postalCode": null,
   "province": null,
   "country": "USA",
   "countryOfBirth": "PGASU",
   "countryOfCitizenship": "UPGSU",
   "visaClass": "DE - PAROLEE (DEFERRED INSPECTION)",
   "portofEntry": "JAI",
   "dateofEntry": "12/21/2017",
   "dateOfBirth": "05/25/1964",
   "gender": "FEMALE",
   "ssn": null,
   "i94AdministeredNumbered": 101987654321,
   "passportNumber": "VTC0LQ1VE56D1P8CL654",
   "fbiNumber": "366852000000",
   "driversLicenseNumber": "LEN8492TM902NN17B8M0",
   "fingerPrintCode": "ENFAQSAPETRTTEASCMTS",
   "identificationFin": 9173,
   "applicationType": "ONE_A",
   "numberOfTrips": "More than one trip",
   "explanationOfEligibility": "My parole is expiring and I am filing for a new one.",
   "signature": null,
   "signatureDate": "02/26/2020",
   "phoneNumber": "571-123-5555",
   "purposeOfTrip": "I would like to attend my sister's wedding and visit additional family members.",
   "countriesVisiting": "Iceland",
   "dateOfDeparture": "05/15/2021",
   "lengthOfTrip": 34,
   "inProceedings": "false",
   "previouslyIssued": "false",
   "deliveryAddress": "1643 Parkcrest Circle",
   "deliveryAddress2": "STE 100",
   "deliveryCity": "Reston",
   "deliveryState": "VA",
   "deliveryZipCode": "20191",
   "deliveryPostalCode": null,
   "deliveryProvince": null,
   "deliveryCountry": "USA",
   "supportDocument": [{
        "id": "SSNSEUESTNRTTSMTSTCS",
        "formType": "I-131",
        "name": "Copy of Driver's License",
        "dateSubmitted": "02/26/2020",
        "status": "Rejected",
        "url": "ACD_BEFG"
        }
    ]
 },
 {
   "anumber": "A827972941",
   "applicantId":"517b079a-1027-4935-a3d2-72f6a065f727",
   "submissionStatus": "SUBMITTED",
   "submissionDate":"11/03/2018",
   "formNumber":"2021_I131_X5",
   "fieldControlOffice": "VUO",
   "dateFileOpen": "11/02/2018",
   "lastName": "Sheehan",
   "firstName": "Seamus",
   "middleName": null,
   "mother": "Elizabet",
   "father": null,
   "akaLastName": "Bins",
   "akaFirstName": null,
   "inCareOf": null,
   "address": "600 W Schuylkill Road",
   "address2": null,
   "city": "Pottstown",
   "state": "PA",
   "zipCode": "19465",
   "postalCode": null,
   "province": null,
   "country": "USA",
   "countryOfBirth": "RECUX",
   "countryOfCitizenship": "PZNBT",
   "visaClass": "DA - ADVANCE PAROLE (DISTRICT AUTH)",
   "portofEntry": "FJQ",
   "dateofEntry": "04/18/2012",
   "dateOfBirth": "10/01/1934",
   "gender": "FEMALE",
   "ssn": "765-140-197",
   "i94AdministeredNumbered": 83266600030,
   "passportNumber": "BE74QF70N805ZT3FIHYY",
   "fbiNumber": "Y23P8JI7ZC1I",
   "driversLicenseNumber": "BABYVAT04OT668D9TNP3",
   "fingerPrintCode": "MPLLLHRYXLDFVPCWDGOR",
   "identificationFin": 5303603504,
   "applicationType": "ONE_B",
   "numberOfTrips": "More than one trip",
   "explanationOfEligibility": "I am on an H-1 temporary work visa.",
   "signature": null,
   "signatureDate": "11/19/2020",
   "phoneNumber": "267-123-5555",
   "purposeOfTrip": "I would like to visit my wife for her birthday.",
   "countriesVisiting": "Bolivia",
   "dateOfDeparture": "07/13/2021",
   "lengthOfTrip": 20,
   "inProceedings": "false",
   "previouslyIssued": "false",
   "deliveryAddress": "600 W Schuylkill Road",
   "deliveryAddress2": null,
   "deliveryCity": "Pottstown",
   "deliveryState": "PA",
   "deliveryZipCode": "19465",
   "deliveryPostalCode": null,
   "deliveryProvince": null,
   "deliveryCountry": "USA",
    "preparer": {
        "lastName": null,
        "firstName": null,
        "businessName": "Test Business",
        "address": "Address",
        "address2": "Line 2",
        "city": "My City",
        "state": "LA",
        "zipCode": "70119",
        "postalCode": null,
        "province": null,
        "country": "U.S.",
        "phone": "504-555-1212",
        "phoneExt": null,
        "email": "email@test.com",
        "signature": "A Tester",
        "date": "2021-03-31"
    },
   "supportDocument": [{
        "id": "HOYDFHXDFZPCUSBRFMPT",
        "formType": "I-131",
        "name": "H1 Visa",
        "dateSubmitted": "11/20/2020",
        "status": "Accepted",
        "url": "GEG_EADH"
        }
    ]
 }
]
)
EOF